server:
  port: 8761   # default Eureka server port

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false   # Don't register the server itself
    fetch-registry: false         # Don't fetch registry from itself
  server:
    enable-self-preservation: false  # Optional: disable for dev (not prod)
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info   # Only expose safe endpoints
  endpoint:
    health:
      show-details: always     # Show db/kafka/elasticsearch health in /actuator/health
